### ISSUE TITLE
Discord Claims and Icon

### ISSUE THREAD

**Issue by l3oat** [gipsy-king/civmap-client#101]
Discord wishes to be on Txapu.

Coords: 6350, -1250

Sub: www.reddit.com/r/CivDiscord

Permission from Fellowship for the land:
www.reddit.com/r/CivDiscord/comments/39isyg/announcement_the_founding_of_discord

Land Claims (Just this island):
https://i.imgur.com/jC3NPrZ.jpg

Preferred Colors:

1st choice: Light Orange

2nd choice: Dark Blue

3rd Choice: Dark Orange

**Comment by RailsDev42** [comment]
Added in my next pull. Salmon Pink. ;)
