### ISSUE TITLE
Updated Chan Land Claims

### ISSUE THREAD

**Issue by l3oat** [gipsy-king/civmap-client#107]
A whole host of new land claims, I wasn't quite sure how to mark them so here's the image containing them all.

https://i.imgur.com/XP9UbOI.png

Nations included:

- Lux Federation (Dark Blue)

- National Socialist Empire of Polynesia & Polynesian Protected Territory (Orange & Purple)

- Bielefeld (Green)

- Neustria (Red)

- Cian (Cyan)

- Atlas (Yellow)

- Clacton (Light Blue)

**Comment by gipsy-king** [comment]
Please see readme for submitting claims, sorry.
