### ISSUE TITLE
Switch some cities to inactive/abandoned

### ISSUE THREAD

**Issue by jj117** [gipsy-king/civmap-client#112]
Viridian and Intis are both abandoned.

Fairly certain Vale and Olympia are also abandoned.
Kaiserin's old location is abandoned.

**Comment by RailsDev42** [comment]
Did you attempt to contact leaders from any of these cities?

What is Kai's old location?

**Comment by jj117** [comment]
Viridian and Intis are confirmed

**Comment by RailsDev42** [comment]
Mkay. I'll get around to it soon. In the meantime, if you'd like to pester the others I might be able to include it in the same push?

**Comment by jezzaindahouse** [comment]
Vale and olympia are abandoned - i can confirm. Carbon, new augusta, commonwealth, hogeklif and donetsk are also inactive

**Comment by RailsDev42** [comment]
Cool. Thanks.

Also, I contacted the owner of Arakeen and they admitted it's basically dead too.

**Comment by jj117** [comment]
Kaiserin's old location - just south of volterra/east of SPQR

**Comment by Jhillthegreat** [comment]
Ancora is also no longer in active, it is a town under Volterra now
