### ISSUE TITLE
Add Kompound (city)

### ISSUE THREAD

**Issue by jj117** [gipsy-king/civmap-client#114]
Type: city
Name: Kompound
800, 9650
Flag: unknown
Abandoned: Yes
URL: 8ch.net/civ/

**Comment by RailsDev42** [comment]
I've processed most of your city requests. Thanks for being concise and having all the right information.

Just so you know, I've not added the non-reddit links as I believe the real purpose of the 'reddit' json-tag is to point at subreddits, not at other sites on the net we don't know are safe to browse and may host unsuitable content.

**Comment by gipsy-king** [comment]
@RailsDev42 see Viridian, there is another prop "url" where you can put in any url.

**Comment by RailsDev42** [comment]
Thanks @gipsy-king  - so you're happy to add any URL's suggested? May want to add a disclaimer that url's may not be suitable for work / life and that viewers visit them at their own risk?

@jj117 - please submit new issues and I'll add them.
