### ISSUE TITLE
CKR Cities

### ISSUE THREAD

**Issue by novakaiserin** [gipsy-king/civmap-client#119]
Land claims coming in a few days; but for now here are coords of our cities:

Essen: -3880, 13340
Albion: -3800, 12070
Iserlohn: -4000 14490

Thanks :)

Side note, can you make a star instead of circle for the Capitol cities?

**Comment by RailsDev42** [comment]
Thanks Nova. That's a good suggestion but you might want to raise it as a separate issue for Gipsy to look at because when I finish the patch, this issue will vanish.

**Comment by novakaiserin** [comment]
Just open up another issue then and suggest the capitol thing then?

**Comment by RailsDev42** [comment]
Yeah, basically.
