### ISSUE TITLE
Too many towns are labelled as cities.

### ISSUE THREAD

**Issue by CodingMonkeyXYZ** [gipsy-king/civmap-client#121]
The map is packed with cities yet most of these have about 1 person in them. Consequently at a high level, the map is crowded. When we zoom in, we can see towns like 'N'. I suggest cities that are part of a larger state that has a capitol be labelled towns instead. Also cities with a tiny population and tiny land claims that are new or dead can be downgraded to 'towns' too.

Suggestions anyone?

First person to say Venice, get's pearled.

**Comment by RailsDev42** [comment]
Also, @gipsy-king - I was wondering if there is or could be another type other than 'city' or 'town' that we could use to label the area, like 'state' or something?

**Comment by RailsDev42** [comment]
Of course, if you have a Cathedral, you're a city. :+1:

**Comment by Xavter** [comment]
Strongly agree that this needs to be addressed. Places like Lux, Brimstone, Tel Aviv, Balkania, Hogeklif and more need to be made smaller. People will always want to promote their towns as "The Most Populated And Significant Town On The Entire Map" but it's pretty easy to see that a small group of reviewers could determine which ones really deserve to be labeled as cities.

Additionally, a lot of towns need to be labeled as inactive. Wish these issues would be fixed sooner.

**Comment by RailsDev42** [comment]
Maybe I could host some sort of survey? I expect I'll take a ton of crap for acting on that (towns don't like being called towns when they think they're empires) but such is life. I'll have a think about designing one.

While I've got your attention though, could you please take a look at the most recent issue about working with GIT and the project?

**Comment by RailsDev42** [comment]
Perhaps I need some sort of team of explorers willing to visit these places? Maybe I could design a points-based scoring system?

**Comment by benjajaja** [comment]
You're exactly right, few people want to run only a town, they want to be called city to attract settlers.
It's also not clear how many players, buildings or amoutn of activity could define a city.

Any suggestions a welcome! Also if you decide on something, since I am not active right now and also the "owner" of the map, I am willing to take flak for "demoting" irrelevant locations to towns. Just pm me on reddit if you want.
