### ISSUE TITLE
Working with the sub modules

### ISSUE THREAD

**Issue by RailsDev42** [gipsy-king/civmap-client#125]
Say I want to merge in tiles myself. I've managed to get the technology to work but I'm a bit new to git and this whole 'submodule thing' has me utterly confused.

Am I right in thinking I need to fork not only this project but all the sub modules too?

Then I clone my fork to my development environment and edit the '.gitmodules' config file to reference my forked clones of yours and run the synch command?

    git submodule sync

then I suppose I follow the rest of your instructions from this point...

    git submodule init
    git submodule update --remote
    npm install
    bower install

Now I can merge my tile data, and run the journeymap.py from the project root and check it looks ok.

The only issues here is that it seems to have lost some data I already contributed and I have to force overlaying of data with the 'over' option on the merge script, otherwise the older, low-res data gets put on top.

Then I suppose to give you the updates, I should go into the relevant submodules and do a git commit and push and then create a pull request for those forks on github?

@gipsy-king ...or would you rather keep responsibility for all this yourself and just accept the zipped data?

Cheers.

**Comment by gipsy-king** [comment]
To generate you have to clone the submodules, yes. You only need to commit
to the "data" submodule, ignore the "tiles" sm in public/, it's better not
to add redundant commits there. Tiles will generate cirrectly from
data/máster.

BTW I don't have internet at home now, so I can't upload sorry, I hope I
get connected this weekend.

**Comment by RailsDev42** [comment]
Damn that sucks, hope you get connected soon.

Thanks for answering. I think I'm getting closer to a working solution so I might be able to provide some decent terrain soon.

Any idea why my Venice terrain update wasn't in the project?

**Comment by gipsy-king** [comment]
I thought venice got updated in the last update?

**Comment by RailsDev42** [comment]
Yeah it did, exactly. When I followed your instructions and dumped the Thule and SW area I collected into the data directory, did the merge and then ran the journeymap.py file from the project root, it seemed to revert back to the old Venice terrain. Although Thule and the SW were added ok.

I'll try it again when I get this sorted but it looks like either the Venice data isn't checked in to the master or somewhere along the line there was a bug that reverted the change when I ran the scripts.

**Comment by gipsy-king** [comment]
If theyre in máster, they should get on the map from journeymap.py. if not,
that's a bug. Check if merge.py really put your tiles in máster, the
tinestamps are a pita because theyre not tracked by git. For voxelmap I
added a tirmstamp flatfile to keep track I think.

**Comment by RailsDev42** [comment]
Well I've just done a clean install and ran all the scripts, after running the map locally, I can see the updated Venice terrain is missing. I'll run my new terrain through in a bit and see if it updates master. If I remember right though, you don't see the tiles after a merge, only after running 'jurneymap.py'.

**Comment by gipsy-king** [comment]
That's correct

**Comment by RailsDev42** [comment]
Ok, I just renamed master to _master and made a new dir called master then ran
      python merge.py Ven1 over

and it populated the master dir.

**Comment by RailsDev42** [comment]
I just ran it again with the original master dir. I can see it's merged my stuff in ok. I think maybe the Venice terrain update just wasn't checked in or something?

**Comment by RailsDev42** [comment]
I'll just re-process them while I'm doing Thule, etc.

**Comment by RailsDev42** [comment]
Followed your instructions but I'm still getting 'detached HEAD' on the submodule. :(

**Comment by gipsy-king** [comment]
I think you can probably just chevkout máster inside the sm

**Comment by RailsDev42** [comment]
Yeah that worked, thanks! I've submitted a pull request on the journeymap submodule with lots of new terrain. A bit more on the way later.

https://github.com/gipsy-king/civmap-journeymap/pull/6

I'll close this.
