### ISSUE TITLE
Volterra Map Tiles

### ISSUE THREAD

**Issue by Jhillthegreat** [gipsy-king/civmap-client#19]
I have some of the Volterran map tiles, but not all. https://www.dropbox.com/s/ijdjcawmfqrspd5/day.rar?dl=0
Thank you, 
Jhill1.

**Comment by gipsy-king** [comment]
added

**Comment by Jhillthegreat** [comment]
Thank you, but some of the tiles did not work, such as all of Ancora, which is owned by the Volterran Empire, and the mooshroom island was half added. 

Sorry for the inconvenience.

**Comment by gipsy-king** [comment]
Oh I see, it must be because there was a bad merge recently, so some timestamps are incorrect - the merge script thinks some existing tiles are newer than they should be. Will merge again later.

**Comment by gipsy-king** [comment]
should be fixed now

**Comment by Jhillthegreat** [comment]
Thank you
