### ISSUE TITLE
[City Addition Request] Balkania

### ISSUE THREAD

**Issue by Uyuxo** [gipsy-king/civmap-client#20]
City or town: City
Name: Balkania
Coords: -4410, -12246
Flag: [http://imgur.com/LrVO1mZ](http://imgur.com/LrVO1mZ)
Subreddit: [reddit.com/r/balkania](reddit.com/r/balkania)
Desired two-letter code: BK
Balkania would greatly appreciate a circle on your fine map. Balkania stronk.

**Comment by gipsy-king** [comment]
so you want it changed from town to city? because it already has been updated the other day.

**Comment by Uyuxo** [comment]
Sponge just said he wanted a big circle on the map, because right now it only shows Balkania if you zoom in towards it.

**Comment by gipsy-king** [comment]
ok...
