### ISSUE TITLE
City Addition Request

### ISSUE THREAD

**Issue by Jhillthegreat** [gipsy-king/civmap-client#32]
*Type: Town
*Name: Vendemmia
*Coordinates: (-8506,-8931)
*Flag: http://i.imgur.com/V2VlZrA.png

The Volterran Empire also has a Civball now we wish added, http://i.imgur.com/3UpKZAY.png

Also, Ancora is also no longer an inactive city. May I also post the coordinates for the rails exactly, Im not sure how to "draw them".

Jhill1

**Comment by gipsy-king** [comment]
@Jhillthegreat for the civball, you'll have to do a pull request with this file edited: https://github.com/gipsy-king/civmap-client/blob/master/public/img/civballs.png

**Comment by Jhillthegreat** [comment]
Alright, can I also make a post with the rail coords or do I have to "draw" them? (im really new to github so im not sure exactly what im doing)

**Comment by gipsy-king** [comment]
If you could post a set of coordinates, the points of the raíl líne, that would help me a lot. One coord per líne or something like that. Also the líne has to be accurate as to where it actually runs. Thanks!

**Comment by Jhillthegreat** [comment]
Volterra - Vendemmia rail
Starts at -7197 -9202, -8179, -9202, -8179 -8942, -8224 -8941, -8224 -8928, -8300, -8928, -8300, -8920, stops at -8500, -8920.
Volterra - Ancora rail Starts -7159 -9200, -6880 -9200,-5035 -7355, -5035 -7155, -5033 -7155, Ends -5033 -7128.
Ancora - Harvest line Starts -5033 -7128, -5033 -7119,-4885 -7119, ends at -4643 -4877

**Comment by gipsy-king** [comment]
The ancora-harvest line is wrong, the last coordinate is somewhere below Orion. The other two are good.

**Comment by Jhillthegreat** [comment]
I am traveling there to check the last one, I must of hit the wrong key.

**Comment by Jhillthegreat** [comment]
Ancora-Harvest
-5033 -7128, -5033 -7119, -4885 -7119, -4643 -6877

**Comment by Jhillthegreat** [comment]
I have fixed the coords

**Comment by gipsy-king** [comment]
Oh sorry, will update today

**Comment by Jhillthegreat** [comment]
Thank you

**Comment by gipsy-king** [comment]
sorry again, I will update this weekend :octopus:
