### ISSUE TITLE
City Addition Request

### ISSUE THREAD

**Issue by DiRtYZeBrA** [gipsy-king/civmap-client#41]
Type: Town
Name: Casper
Location: (-6100, -2900)
Subreddit: reddit.com/r/Civcraft_Casper
Two Letter Code: Cp
[Flag](http://imgur.com/hJ6rmQF)
Is Active: Yes

**Comment by gipsy-king** [comment]
Would you happen to want Orion land claim there too?

**Comment by DiRtYZeBrA** [comment]
No this is my own thing, Orion isn't involved at all. I'll make a land claim soon
