### ISSUE TITLE
Rail Line Request

### ISSUE THREAD

**Issue by DiRtYZeBrA** [gipsy-king/civmap-client#45]
Rail line for Casper

Rail starts in Freeport at (-5706, -3434)
Turns west at (-5706,-2920)
Ends at (-6070, -2920)

[Drawing](http://imgur.com/SaEWxHd)

**Comment by gipsy-king** [comment]
Are there any rails to Freeport? FYI there's a single rail line from Ñ (north of Freeport) to Orion.

**Comment by DiRtYZeBrA** [comment]
There is a rail from Etherium to Freeport but I don't know the coords. It goes into that same building as the new rail I dug though so I know that's the rail station in Freeport
