### ISSUE TITLE
FSR submitted conflicting claims

### ISSUE THREAD

**Issue by hlprimm** [gipsy-king/civmap-client#52]
https://www.reddit.com/r/Civcraft/comments/3ef1j9/garundistan_is_not_has_never_been_and_will_never/

MegraLew submitted a conflicting claim, not sure what you think is best to do in this situation. I am not one to choose sides. 

Here is a receipt of his order:

>7/9/2015 12:37:43 CST

>Nation: Federal Socialist Republics

>reddit name: MegraLew

>Color: 4A070C

>Claims: http://pasteboard.co/1PMEETcd.png

>Agreement: yes, our claims do not conflict with anyone elses.

>Agreement: yes, our claims do not contain ocean.

>Agreement: yes, our leaders and neighbors agree our claims are good.

>Agreement: yes I will not add further claims to my submission.  

>Agreement: Yes I agree. If I submit a claim that is disputed, I will pay 30d to /u/ajisai for submitting an erroneous claim.

>Agreement: Yes, I agree to hand deliver or dropchest 30d for /u/ajisai, in game name: hlprimm

>Notes: You just need to remove your land claims from from the TXAPU and ours will be fine, also RogueX7 says draw over olympia's with ours because he doesn't know how to change it

>Approx area of claims: 8000 -3800       

>Has paid? Pending payment.

**Comment by gipsy-king** [comment]
fixed with 62c0738
