### ISSUE TITLE
Some requests to change the map.

### ISSUE THREAD

**Issue by Magmus** [gipsy-king/civmap-client#69]
Change Iria, it has a Nether Factory, and add this flag: https://wiki.civcraft.co/lib/exe/fetch.php?t=1440166857&w=500&h=337&tok=a49794&media=iria_flag.jpg 

Also add Agricola, it is at -3040 6180, and use this as it's flag: https://wiki.civcraft.co/lib/exe/fetch.php?t=1440163133&w=500&h=333&tok=d47c6c&media=beneshire_flag.png

Edit: You can also use this flag for Agricola: https://wiki.civcraft.co/lib/exe/fetch.php?cache=&media=agricola_flag.jpg

**Comment by RailsDev42** [comment]
Is Iria's NF public? If not, you should submit another chance request because I've assumed it is.

I've also assumed Agricola is an active city.

I've added this all to my latest Pull request. Please check it when it goes live.
