### ISSUE TITLE
Add Azkaban to cities

### ISSUE THREAD

**Issue by TealNerd** [gipsy-king/civmap-client#70]
City
Azkaban
0,-15000
no flag sorry

additional info:
2 letter code: AZ

**Comment by RailsDev42** [comment]
Hmm. Shady as heck but ok, done.

**Comment by TealNerd** [comment]
Why is this shady?

**Comment by RailsDev42** [comment]
No flag, no subreddit, never heard of it, right on the world border.... okkaaaayyyy. :)

**Comment by TealNerd** [comment]
It has a subreddit, the subreddit is just private

**Comment by RailsDev42** [comment]
You can still add it here. Not a bad idea if someone needs to contact the leaders for some reason.

**Comment by TealNerd** [comment]
I'd rather not

**Comment by RailsDev42** [comment]
Alright. Done.
