### ISSUE TITLE
Add Abandoned to city list

### ISSUE THREAD

**Issue by TealNerd** [gipsy-king/civmap-client#71]
City
Abandoned
2000, -14000
Flag image link, preferrably "imgur" about 200x100 pixels

/r/CivAbandoned
code: AB
not abandoned

**Comment by RailsDev42** [comment]
This is a city, called 'Abandoned', that's NOT Abandoned?

**Comment by RailsDev42** [comment]
Could you please provide an actual flag image?

**Comment by TealNerd** [comment]
lol i meant to include a flag link idk why i didnt. Anyway now our flag is being redone so i dont have one yet

**Comment by RailsDev42** [comment]
Is it in the sea? http://txapu.com/#8/2000/-14000

Doesn't seem to be anything at those coords - or is it out of date?

**Comment by TealNerd** [comment]
it's the mushroom island

**Comment by RailsDev42** [comment]
That's more like 1800, -14080? Ok, added it.
