### ISSUE TITLE
Riverford-Holy Tree Railway

### ISSUE THREAD

**Issue by neondan99** [gipsy-king/civmap-client#91]
http://imgur.com/s3GH9HN

Sorry for the huge influx of different railways but I promise this one's the last, lol. Technically it isn't actually a railway (it's under construction) but as it will almost certainly be completed by tomorrow I thought I'd upload it along with all the others.

Edit: a) +4142, +2046. b) +4417, +1789. c) +4417, +1534.

**Comment by RailsDev42** [comment]
Ah, yeah, you see, this is the sort of thing I was talking about on my post. For railways, we need to add them by coordinates. So someone has to provide a list of line start and end points (x,z) for each individual bit of rail. Could you please go through all your rail issues and add that? I'm happy to add the code myself and submit a pull request once you do.
