### ISSUE TITLE
Add Ember Island Please

### ISSUE THREAD

**Issue by LPTSO** [gipsy-king/civmap-client#93]
Hi, I own a little a town on this mushroom island. It's called Ember Island. It's coords are -5750, -9330. It's part of Volterra. Thank you!

**Comment by RailsDev42** [comment]
You just want a town name at those coords? Any flag, subreddit, netherfactory, etc?

**Comment by Jhillthegreat** [comment]
Sorry LP, I thought I put this up a while ago. Flag, http://i.imgur.com/V2VlZrA.png .

**Comment by LPTSO** [comment]
Just the town name would be fine. I don't have a subreddit or a netherfactory. I'll use the flag Jhill posted until I can come up with my own regional flag.

**Comment by RailsDev42** [comment]
ok, will do.

**Comment by RailsDev42** [comment]
note to self - comited.
