### ISSUE TITLE
ATN: Monkey

### ISSUE THREAD

**Issue by jezzaindahouse** [gipsy-king/civmap-client#94]
http://txapu.com/?svg=http://imgh.us/claims_9.svg

**Comment by jezzaindahouse** [comment]
SPQR and Balkania should be added!

**Comment by RailsDev42** [comment]
k, i'll see what I can do.

**Comment by RailsDev42** [comment]
Pull request submitted.

**Comment by RailsDev42** [comment]
mistake: I need to redo

**Comment by RailsDev42** [comment]
@gipsy-king - I think you can close this, it should be included in my latest pull, I just forgot to mention it.
