### ISSUE TITLE
Gipsy: please clarify instructions for adding JourneyMap data.

### ISSUE THREAD

**Issue by RailsDev42** [gipsy-king/civmap-client#95]
Looks like the readme file was altered recently and the line 'You can add what you have mapped with voxelmap' replaced the bit about Journeymap. Is it even possible to contribute VoxelMap data and do you still prefer JourneyMap format?

If you want JourneyMap data, could you please re-add the instructions for that format. I think it's just

Go to .minecraft\journeymap\data\mp\CivCraft\DIM0 and archieve the 'day' folder.

**Comment by gipsy-king** [comment]
Journeymap, voxelmap can generate heightmap and biomemap only, atm without a renderer.

The path for JM is correct.
