### ISSUE TITLE
Rosewall Claims and Icon

### ISSUE THREAD

**Issue by jezzaindahouse** [gipsy-king/civmap-client#99]
Rosewall wishes to be on Txapu.

Coords: 1100, -5700

Sub (private) https://www.reddit.com/r/CivRosewall

Flag: http://i.imgur.com/aV78A2X.jpg

Land Claims: http://i.imgur.com/CJfA07V.jpg

Preferred colour: 1st - black, 2nd - grey, 3rd - red. Or a combination (preferably black and red).

**Comment by RailsDev42** [comment]
Get your coat issue, you've pulled.
